CommonJobs/CommonJobs

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/CalificationsDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/EmployeeSearching/EmployeeToEvaluate_Search.cs, source/CommonJobs/CommonJobs.Domain.EvalForm/EmployeeEvaluation.cs
This command will be in charge of retrieving the list of califications depending on the user being evaluated, the loggedUser and the period.
It has to determine if the user is trying to see the auto-evaluation, the evaluation as a responsible, the evaluation as an evaluator of if the evaluation is ready for devolution.
Can you review @andresmoschini @AlphaGit @joseguti84 @sofipacifico
Thanks!
PS: Next PR will contain the logic to save/finalize the evaluations. With that we should be able to complete the full flow.
=> Get Califications Command

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateCalificationsCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateEvaluatorsCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/CalificationsDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/EvaluatorsUpdateDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/UpdateCalificationDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/UpdateEvaluationDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/EmployeeSearching/EmployeeToEvaluate_Search.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs
This command will save the califications of the evaluation. It checks the user logged in and updates whats needed.
Can you please review @andresmoschini @AlphaGit @joseguti84 @sofipacifico
Thanks!
=> Save califications command.

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationTemplateCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateEvaluatorsCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/UpdateCalificationDTO.cs, source/CommonJobs/CommonJobs.Domain.EvalForm/EvaluationCalification.cs, source/CommonJobs/CommonJobs.Domain.EvalForm/Template.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/EvaluationsAreaRegistration.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Models/Calification.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Shared/_Layout.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/common.js
- Template: Name to each groupKey in the "GetEvaluationTemplateCommand.cs"
- Data mapping in viewModel
- Render all califications items dynamically from viewModel
- Improve the CSS styles
- Average calculation
=> Calification page (In progress)

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
**Done
*General  user (Responsible, Calificators and Autoevaluations) can see a comment field where they can add a general comment. In Company case the template is diffetent, the company user can see a comment field with three different types of comments.
*Save data!
=> Comment in evaluation

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs
=> Add anotations for security reasons (EmployeeManagers)

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
**Done
*Added logic to show the comments of the evaluator and califications in the company evaluation!
*Change div for textarea
*Improve textarea style
=> Logic to show comments in the company Evaluation!

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateCalificationsCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/UpdateEvaluationDTO.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodEvaluation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
* Fix some typo
* Add logic to the finish calification button
* Validation on calification fields
* When the average is '0', it's replace with '-'
* Improve the underscore chaging use. 
* Add url to "Calificar" and "Ver Calificación" links
=> Califications flow

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs
When trying to access evaluations and calification screens (controller level).
Can you please review  @andresmoschini @AlphaGit @joseguti84 @sofipacifico?
=> Authorization behaviour

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/CalificationsDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/CalificationsEvaluationDto.cs, source/CommonJobs/CommonJobs.Domain.EvalForm/EmployeeEvaluation.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Models/Calification.cs
Can you please review @andresmoschini @AlphaGit @joseguti84 @sofipacifico?
=> Fix seniority and position

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/StartDevolutionCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Domain.EvalForm/EmployeeEvaluation.cs
Simple Command to start devolution.
Please review @andresmoschini @AlphaGit @joseguti84
=> Add command to start devolution

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs
I refactored this command in order to fetch the correct califications for every case. Also added some security (that I think it could be extracted to controller level but with some more refactoring in order to avoid fetching more data from the DB).
Can you please review @andresmoschini @AlphaGit @joseguti84 @sofipacifico
=> Get Evaluation califications refactor.

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs
The dashboard wasn't fetching any employees for the calificators. I fixed that.
Please review! @andresmoschini @AlphaGit @joseguti84
=> Fix to fetch the employees a calificator can evaluate.

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/CalificationsEvaluationDto.cs
Simple change in order to provide a list of evaluators when fetching califications.
Please review @andresmoschini @joseguti84
=> Add evaluators list to calificationsDto

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
I changed the way to get the name of calification's evaluators
=> Evaluators list

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
I added an average column when the user is responsible or company type
=> Average column

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Shared/_Layout.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
* Fix an issue when the calificator user see the dashboard, the text of calificate link is wrong. 
* Add a Layout view model to use in the Calification's header.
=> Bug fixing

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateCalificationsCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/UpdateEvaluationDTO.cs
Please review @andresmoschini @joseguti84
=> Add the possiblity to finish the evaluation.

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEmployeesForEvaluationCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationTemplateCommand.cs
Also fix evaluation creation screen order.
Can you please review @andresmoschini @joseguti84 @sofipacifico?
=> Fix template calification names and descriptions. 

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateCalificationsCommand.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
* Enable to edit califications of Company and Autoevaluated
* Save the califications and comments when the evaluation is on "Ready for devolution" status
=> Ready for devolution flow

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodEvaluation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Shared/_Layout.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js, source/CommonJobs/CommonJobs.Mvc.UI/CommonJobs.MVC.UI.csproj
* Include some images in the project
* Improve some small css styles
=> Small changes

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodEvaluation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/admin.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/common.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
* Show all comment to evaluated user when the evaluation is "Ready for devolution"
* Improve the grids sorting
=> Evaluated user

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
* Added pop-up to show a message before the evaluation finishes
=> Add a pop-up in the evaluation

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateEvaluatorsCommand.cs
Can you please review @andresmoschini @joseguti84?
Thanks!
=> Fix bug about evaluators being added at their own evaluations.

source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
* Refactor to this PR: https://github.com/CommonJobs/CommonJobs/pull/424
* Add validation in calificator manager
=> Fix small details

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/EmployeeEvaluationDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/EmployeeSearching/EmployeeToEvaluate_Search.cs, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
This PR include logic on BE and FE
=> Fix a bug with calificators flow in dashboard page

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
* Add background color to califiaction value
* Add the item number
* Change the text of evaluation link depending on the evaluations status
* Remove all 0 after "." in the califications values
=> Some changes from demo feedback

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatedEmployees.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/EmployeeEvaluationDTO.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs
Dashboard and controller method for the EmployeeManagers.
Can you please review? @andresmoschini @AlphaGit @sofipacifico @joseguti84
=> Dashboard for EmployeeManagers (backend)

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodEvaluation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
* Added spinner until the entire page is loaded
* TODO: add a modal to show different errors (future tags)
=> Add loader

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEmployeesForEvaluationCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/StartDevolutionCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateEvaluatorsCommand.cs, source/CommonJobs/CommonJobs.Application.MyMenu/GetEmployeeMenuCommand.cs, source/CommonJobs/CommonJobs.Application.MyMenu/GetEmployeeMenusCommand.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs
Removed the wait for non stale results from Raven queries.
Can you please review? @andresmoschini @AlphaGit
=> Remove "WaitForNonStale..." from evaluations queries.

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css
* Imporve UI for information icon in the evaluation
=> Improve UI 

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
* Implement a way to highlight the row being edited, done!
* UI in progress! (Tomorrow Jose will do a new design)
=> Highlight the row being edited

source/CommonJobs/CommonJobs.Mvc.UI/CommonJobs.MVC.UI.csproj
* Added information icon in the project
=> Added images in the project

source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/admin.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
Please review @AlphaGit @andresmoschini @joseguti84 @sofipacifico!! 
Take into account that front-end isn't my strong suit! =D
=> Adds ajax failed alert responses.

source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
*Hide spinner before to show an alert for an ajax error
=> Fix spinner after ajax error

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Models/ReportDashboard.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/DashboardRecursosHumanos.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/ReportDashboard.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard-human-resources.js, source/CommonJobs/CommonJobs.Mvc.UI/CommonJobs.MVC.UI.csproj
* Dashboard for human resources about evaluated people (layout and logic), done!
* To Do: Remove the line with the hardcode period
@andresmoschini @AlphaGit @Gkolocsar  @joseguti84 
Could you take a look? Thank you!
=> Dashboard for Human Recourses

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/UpdateEvaluatorsCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.MyMenu/CommonJobs.Application.MyMenu.csproj, source/CommonJobs/CommonJobs.Application.MyMenu/EmployeeMenuByMenuId_Search.cs, source/CommonJobs/CommonJobs.Application.MyMenu/GetEmployeeMenuCommand.cs, source/CommonJobs/CommonJobs.Application.MyMenu/GetEmployeeMenusCommand.cs, source/CommonJobs/CommonJobs.Application/CommonJobs.Application.csproj, source/CommonJobs/CommonJobs.Application/EmployeeSearching/EmployeeByUserName_Search.cs, source/CommonJobs/CommonJobs.Infrastructure.RavenDb/CommonJobs.Infrastructure.RavenDb.csproj, source/CommonJobs/CommonJobs.Infrastructure.RavenDb/Schedule/ExecuteScheduledTasks.cs, source/CommonJobs/CommonJobs.Infrastructure.RavenDb/Schedule/ScheduleTask_Search.cs, source/CommonJobs/CommonJobs.Mvc.UI/Controllers/AccountController.cs, source/CommonJobs/CommonJobs.Mvc.UI/Controllers/GoogleAuthenticationController.cs, source/CommonJobs/CommonJobs.Mvc.UI/Global.asax.cs
Improve User, Employee, EmployeeMenu, EvaluationCalification and ScheduleTask searches by adding indexes and/or modifying how the system does the actual query.
This can lead to a really nice performance improvement. Can you please review @AlphaGit @andresmoschini @sofipacifico?
Thanks!
=> Index improvements

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml
* Small fix to show comments to evaluators after the evaluation is already finished! (deleted filter in template)
=> Fix comments for evaluators

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs
Employee Managers were receiving a 403 when trying to access a finished evaluation. Now it's fixed.
Can you please review? @andresmoschini @AlphaGit @sofipacifico
=> Fix HHRR permissions when trying to access a finished calification.

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/ReportDashboard.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Shared/_Layout.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css
* Add title and Breadcrum for Human Resources Dashboard
=> Fix ui dashboard rrhh

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
* Deleted "Devolution" 
* Hide columns by defect depending the status of the evaluation
https://docs.google.com/spreadsheets/d/1cxLBGGGaH6hxrtYURDS2DfGuBkuspGzQzLqplG4hKOo/edit#gid=0
*All status looks good as in the doc
*Working on : comments in evaluation of evaluators after is finished by the company
=> Working on Status

source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
* Added logic to show all comments in the evaluators evaluation in readyfordevolution
* Improved logic for editable evaluations depending the user
@AlphaGit  @andresmoschini  @Gkolocsar Could you review if you have some time, please? Thanks
=>  Fix bugs in the evaluation

source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/admin.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/common.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard-human-resources.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
* Sort by action in responsible and evaluator dashboard
@AlphaGit @andresmoschini @Gkolocsar Could you take a look?? Maybe you have a better approach!
=> Filter by action

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodCreation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/admin.js
* Verify if the evaluation generated is valid or not, depends that, show different text in pop-up and prevent to send  the ajax though the backend validates the evaluation generated.
* Show a red border in the input if the username and the reponsible is the same.
Could you take it a look, please? @Gkolocsar @AlphaGit @andresmoschini
=> Improve evaluations generated

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GenerateEvaluationsCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/EmployeeSearching/EmployeeToEvaluate_Search.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Models/PeriodCreation.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodCreation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodEvaluation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/admin.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
Hi Andres! I made some changes to allow working with multiple periods. Now you can create evaluations for different periods and also check evaluations by period. Could you review?
=> Periods managment

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs
Minor change to use POST verb instead of DELETE in DeleteEmployeeEvalution and DeletePeriod methods
=> Change http verbs for DeleteEmployeeEvalution and DeletePeriod methods

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
Hi Andres! I added the comment section in each evaluation item. This PR is just to show the comments. An evaluated employee can see its own comment, an evaluator sees his comment and the evaluated employee's one, and finally the Responsable can see all the comments.
Could you review please?
=> Add comment section to the Evaluation view

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/EvaluationsAreaRegistration.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/ReportDashboard.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard-human-resources.js
Hi Andres! here is my code to enable choosing periods in the repot dashboard. Could you review please?
=> Allow view report by period

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/RevertEvaluationStateCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/EmployeeEvaluationDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Helper/RevertEvaluationActionsHelper.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Indexes/EmployeeToEvaluate_Search.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodEvaluation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/ReportDashboard.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
Hi Andrés! Here is my change to allow rolling back in the evaluation state. Could you review please?
=> Allow rollback in evaluation status

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
Hi Andrés! Her is my change to modify the _Finish_ button text when a responsible is evaluating. Could you review?
=> Change finish button text when the responsible is evaluating

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs
@andresmoschini
Just a fast change to make params names similar to the other methods in the controller
=> minor change to keep the same names of parameters

source/CommonJobs/CommonJobs.Infrastructure.Mvc/Authorize/SessionAndExternalRolesAuthorizationBehavior.cs
@andresmoschini
minor fix to cache roles in the httpcpntext
=> cache roles while request is alive

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
@andresmoschini
Hi Andrés!
Here is the change to show general comments leaving them outside the Company comment. Could you review?
=> Improve general comments visualisations

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
Hi Andrés! Here is a small change to allow showing or hiding item comments. Could you review?
=> Show and hide items comments depending on calcifications visibility

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/CalificationsEvaluationDto.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Helper/RevertEvaluationActionsHelper.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
hi Andrés! here is a simple update to avoid modifications in evaluators calification values if the company evaluation has finished. Could you review?
=> Avoid evaluators to update their calcifications if the company evaluation is done

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
Hi andres! this is a minor change to avoid modifications in the comments after Company calification has finished. Could you review?
=> Don't allow comments updates when the company calification has finished

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/ReportDashboard.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard-human-resources.js
Hi Andrés! Here is my change to create a UI to the functionality  _Change Responsible_. Could you review please?
=> Create UI to change an evaluation responsible

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatedEmployees.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/CalificationsEvaluationDto.cs, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/EmployeeEvaluationDTO.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Helper/EvaluationStateHelper.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
Hi Andrés! Here is my change to show the evaluation state in calification view. Could you review?
=> Show state in calification view

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Shared/_Layout.cshtml
Hi Andrés! 
Here is another small change to update the _AutoEvaluation_ button text if teh evaluation of the logged user is _ReadyForDevolution_
=> change auto-evaluation button text if evaluation is Ready for Devolution

entregables/site/Docs/Manual-de-Usuario/Evaluaciones.markdown
Hi andres! here is a small update to the help documentation
=> Update evaluation documentation

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
Hi Andrés! This is a change to warn a responsible if there is any value with decimals different than 5 in the company califications. Could you review please?
=> Notify responsible when company califications have some value with decimals different than 5

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs
Minor fix to solve an error when loading the evaluation dashboard
=> Fix the error of multiple request to the database when opening the dashboard

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatedEmployees.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluatorEmployeesCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.EvalForm/Helper/EmployeeEvaluationHelper.cs
Hi Andrés!
This is the result of what we talk about moving the mapping for EmployeeEvaluationDTO to a new helper class. Could you review it?
=> Create EmployeeEvaluationHelper and move the EmployeeEvaluationDTO mapping to it

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/auto-expandable-value.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/height-updater.js, source/CommonJobs/CommonJobs.Mvc.UI/CommonJobs.MVC.UI.csproj
Hi Andrés!
Here is my code to fox the problem of projects and evaluators not showing when too many. Could you review?
=> Evaluators and projects dont show when too many

source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
Hi Andres! Here is a minor change to alert a user that leaves the page with unsaved changes (users will be happy :laughing:)
=> Alert user when leaving the page with unsaved changes

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/tri-state.js, source/CommonJobs/CommonJobs.Mvc.UI/CommonJobs.MVC.UI.csproj
Hi Andrés! 
Here is my change to modify the calification item switches in order to easily identify those items with comments and to add a switch to show or hide all comments at the same time. Could you review?
=> Improve comment switches

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/Calification.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Content/Evaluations/evaluations.css, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/markdown-markdownHtml.js, source/CommonJobs/CommonJobs.Mvc.UI/CommonJobs.MVC.UI.csproj
Hi Andrés!! I finaly applied MarkDown in the comments area. Could you review please?
=> Add markdown to comments

source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/calification.js
Hi Andrés! 
Here is my change to fix the problem of evaluations not loading. What i did is to return always a company view if the evaluation has finished. Could you review?
=> Return Company View  whenever the evaluation has finished

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEmployeeEvaluationHistoryCommand.cs, source/CommonJobs/CommonJobs.Application.EvalForm/CommonJobs.Application.Evaluations.csproj, source/CommonJobs/CommonJobs.Application.EvalForm/DTOs/HistoricalEvaluationDto.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Helper/EmployeeEvaluationHelper.cs, source/CommonJobs/CommonJobs.Application.EvalForm/Indexes/EmployeeEvaluationHistory_Search.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsApiController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/EvaluationsAreaRegistration.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Models/HistoryDashboard.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/HistoryDashboard.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard-history.js, source/CommonJobs/CommonJobs.Mvc.UI/CommonJobs.MVC.UI.csproj
Hi andres!!! 
I created a History dashboard where a responsible can review previous evaluations of a specific employee. Here is screenshot  oh hod does it looks.
Next step is to link each row to a the calification screen.
=> Create evaluation history dashboard

source/CommonJobs/CommonJobs.Application.EvalForm/Commands/GetEvaluationCalifications.cs, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Controllers/EvaluationsController.cs
Hi Andres!! 
here is a small change to allow a responsible view and old evaluation of his evaluated employee
=> Allow newer responsible to access and view previous evaluations of his evaluated employee

source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/HistoryDashboard.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Areas/Evaluations/Views/Evaluations/PeriodEvaluation.cshtml, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard-history.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
Hi Andrés! Here is another small change, this time to add links to History Dashboard from the Period Evaluation screen and another set of links to the evaluation califications in the History Dashboard
=> Create links to historycal dashboard

source/CommonJobs/CommonJobs.Mvc.UI/CommonJobs.MVC.UI.csproj
A minor fix that will solve the error page that users where receiving when consulting any evaluation history
=> Fix HistoryDashboard.cshtml properties in the CommonJobs.MVC.UI.csproj

entregables/site/Docs/Manual-de-Usuario/Evaluaciones.markdown
I added information about the Revert Action functionality in the evaluation dashboard
=> Update documentation including RevertActions for evaluation states

source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/auto-expandable-value.js, source/CommonJobs/CommonJobs.MVC.UI/Scripts/Evaluations/dashboard.js
A minor change to reload the page and get the updated information in evaluation dashboard
=> Fix bug when starting evaluation devolution
